services:
  frontend:
    ports:
      - "${FRONTEND_PORT:-80}:80"

  user-service:
    environment:
      SWAGGER_ENABLED: "true"
      TRACING_SAMPLE_PROBABILITY: "1.0"

  ai-service:
    environment:
      SWAGGER_ENABLED: "true"
      TRACING_SAMPLE_PROBABILITY: "1.0"
      CLAMAV_HOST: ""

  notification-service:
    environment:
      TRACING_SAMPLE_PROBABILITY: "1.0"

  api-gateway:
    environment:
      TRACING_SAMPLE_PROBABILITY: "1.0"
