package com.pravoos.ai.document.internal.service;

import com.pravoos.ai.document.internal.model.entity.Document;
import com.pravoos.ai.document.internal.repository.jpa.DocumentRepository;
import com.pravoos.ai.llm.api.LlmClient;
import com.pravoos.ai.llm.api.LlmOptions;
import com.pravoos.ai.llm.api.LlmResult;
import com.pravoos.ai.shared.config.DocumentSummaryProperties;
import com.pravoos.ai.shared.exception.DocumentNotFoundException;
import com.pravoos.ai.shared.exception.DocumentSummaryFailedException;
import com.pravoos.ai.shared.model.enums.DocumentKind;
import com.pravoos.ai.shared.service.LlmQuotaService;
import java.util.List;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class DocumentSummaryService {

  private static final Logger log = LoggerFactory.getLogger(DocumentSummaryService.class);
  private static final double SUMMARY_TEMPERATURE = 0.2;

  private final DocumentRepository documentRepository;
  private final DocumentTextExtractor documentTextExtractor;
  private final DocumentSummaryStore documentSummaryStore;
  private final DocumentSummaryParser documentSummaryParser;
  private final LlmClient llmClient;
  private final LlmQuotaService llmQuotaService;
  private final DocumentSummaryProperties properties;

  public DocumentSummaryService(
      DocumentRepository documentRepository,
      DocumentTextExtractor documentTextExtractor,
      DocumentSummaryStore documentSummaryStore,
      DocumentSummaryParser documentSummaryParser,
      LlmClient llmClient,
      LlmQuotaService llmQuotaService,
      DocumentSummaryProperties properties) {
    this.documentRepository = documentRepository;
    this.documentTextExtractor = documentTextExtractor;
    this.documentSummaryStore = documentSummaryStore;
    this.documentSummaryParser = documentSummaryParser;
    this.llmClient = llmClient;
    this.llmQuotaService = llmQuotaService;
    this.properties = properties;
  }

  public void summarizeAfterUpload(UUID documentId, String extractedText) {
    if (!properties.enabled()) {
      return;
    }
    try {
      Document document = load(documentId);
      if (!summarizable(document)) {
        return;
      }
      documentSummaryStore.markPending(documentId);
      long tokens = generateAndStore(documentId, document.getTitle(), extractedText);
      llmQuotaService.recordTokenUsage(document.getUploadedBy(), tokens);
      log.info("Document {} summarized on upload ({} tokens)", documentId, tokens);
    } catch (Exception e) {
      log.warn("Auto-summary failed for document {}: {}", documentId, e.getMessage());
      markFailedQuietly(documentId);
    }
  }

  private void markFailedQuietly(UUID documentId) {
    try {
      documentSummaryStore.markFailed(documentId);
    } catch (Exception e) {
      log.warn("Could not mark summary as failed for document {}: {}", documentId, e.getMessage());
    }
  }

  public void regenerate(UUID documentId, UUID requestedBy) {
    if (!properties.enabled()) {
      throw new DocumentSummaryFailedException("Краткое содержание документов отключено");
    }
    Document document = load(documentId);
    if (!summarizable(document)) {
      throw new DocumentSummaryFailedException(
          "Для этого документа краткое содержание не составляется");
    }

    llmQuotaService.assertWithinQuota(requestedBy);
    documentSummaryStore.markPending(documentId);
    try {
      long tokens =
          generateAndStore(
              documentId, document.getTitle(), documentTextExtractor.extractText(document));
      llmQuotaService.recordUsage(requestedBy, tokens);
      log.info(
          "Document {} summary regenerated by {} ({} tokens)", documentId, requestedBy, tokens);
    } catch (DocumentSummaryFailedException e) {
      documentSummaryStore.markFailed(documentId);
      throw e;
    } catch (Exception e) {
      log.warn("Summary regeneration failed for document {}: {}", documentId, e.getMessage());
      documentSummaryStore.markFailed(documentId);
      throw new DocumentSummaryFailedException("Не удалось составить краткое содержание документа");
    }
  }

  private long generateAndStore(UUID documentId, String title, String text) {
    if (text == null || text.isBlank()) {
      throw new DocumentSummaryFailedException("Документ не содержит распознаваемого текста");
    }

    LlmResult completion =
        llmClient.complete(
            DocumentSummaryPrompt.SYSTEM_PROMPT,
            List.of(),
            DocumentSummaryPrompt.userMessage(title, text, properties.maxInputChars()),
            new LlmOptions(null, properties.maxTokens(), SUMMARY_TEMPERATURE));

    DocumentSummaryDraft draft = documentSummaryParser.parse(completion.content());
    if (draft.isEmpty()) {
      throw new DocumentSummaryFailedException("Модель не вернула краткое содержание документа");
    }
    documentSummaryStore.storeReady(documentId, draft);
    return completion.usage().totalTokens();
  }

  private boolean summarizable(Document document) {
    return document.getDocumentKind() == DocumentKind.GENERAL;
  }

  private Document load(UUID documentId) {
    return documentRepository
        .findById(documentId)
        .orElseThrow(() -> new DocumentNotFoundException(documentId));
  }
}
